"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-09

Creates the full initial schema in one migration: patients, providers,
services, appointments, appointment_services (the many-to-many join
between an appointment and its individual service+provider bookings),
and payments.

This migration is hand-written rather than autogenerated from the
SQLAlchemy models (`app/models.py`). It's written to mirror those models
exactly -- column types/nullability and index definitions here should
stay in lockstep with the ORM. In particular, every `create_index` call
below corresponds 1:1 to an `index=True` flag on the matching ORM column;
if a column gains/loses `index=True` in the models, this migration (or a
follow-up one) needs the same change.

Tables are created in FK-dependency order (patients/providers/services
first, since appointments and payments reference them; appointment_services
last among the "leaf" tables since it references appointments, services,
and providers all at once) so that each `sa.ForeignKey(...)` can resolve
against an already-created target table.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- patients: no FK dependencies, so created first -------------------
    op.create_table(
        "patients",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
    )
    # Indexed because analytics queries filter/group patients by marketing
    # source and by signup recency.
    op.create_index("ix_patients_source", "patients", ["source"])
    op.create_index("ix_patients_created_date", "patients", ["created_date"])

    # --- providers: no FK dependencies -------------------------------------
    op.create_table(
        "providers",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
    )

    # --- services: no FK dependencies --------------------------------------
    op.create_table(
        "services",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
    )

    # --- appointments: depends on patients ---------------------------------
    # Note: an appointment intentionally has no service/provider/time
    # columns of its own -- those live one level down, in
    # appointment_services -- since a single appointment can bundle
    # multiple bookings (e.g. consultation -> blood test -> X-ray).
    op.create_table(
        "appointments",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("patient_id", sa.String(), sa.ForeignKey("patients.id"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_appointments_patient_id", "appointments", ["patient_id"])
    op.create_index("ix_appointments_status", "appointments", ["status"])

    # --- appointment_services: the many-to-many join table between --------
    # appointments, services, and providers. This is the hinge of the whole
    # schema: it's what lets one appointment fan out to multiple
    # service+provider bookings, each with its own start/end time.
    # Depends on appointments, services, and providers, so it must be
    # created last among these related tables.
    op.create_table(
        "appointment_services",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("appointment_id", sa.String(), sa.ForeignKey("appointments.id"), nullable=False),
        sa.Column("service_id", sa.String(), sa.ForeignKey("services.id"), nullable=False),
        sa.Column("provider_id", sa.String(), sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_appointment_services_appointment_id", "appointment_services", ["appointment_id"])
    op.create_index("ix_appointment_services_service_id", "appointment_services", ["service_id"])
    op.create_index("ix_appointment_services_provider_id", "appointment_services", ["provider_id"])
    op.create_index("ix_appointment_services_start", "appointment_services", ["start"])

    # --- payments: depends on patients, providers, appointments, services --
    # `service_id` here is the *primary* service billed for the appointment,
    # not every service on it (that full list lives in appointment_services).
    # Not every appointment has a payment (some are unpaid), and payment
    # status (pending/paid/failed) is tracked independently of appointment
    # status (pending/confirmed/cancelled). `amount` is integer cents.
    op.create_table(
        "payments",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("patient_id", sa.String(), sa.ForeignKey("patients.id"), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("appointment_id", sa.String(), sa.ForeignKey("appointments.id"), nullable=False),
        sa.Column("service_id", sa.String(), sa.ForeignKey("services.id"), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_payments_patient_id", "payments", ["patient_id"])
    op.create_index("ix_payments_appointment_id", "payments", ["appointment_id"])
    op.create_index("ix_payments_date", "payments", ["date"])
    op.create_index("ix_payments_status", "payments", ["status"])


def downgrade() -> None:
    # Reverse of creation order, so each drop happens before the table it
    # depends on (via FK) is removed.
    op.drop_table("payments")
    op.drop_table("appointment_services")
    op.drop_table("appointments")
    op.drop_table("services")
    op.drop_table("providers")
    op.drop_table("patients")
